[font]
size = 12.0

[font.bold]
family = "SauceCodePro NF"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro NF"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro NF"
style = "Italic"

[font.normal]
family = "SauceCodePro NF"
style = "Regular"

[shell]
program = "/usr/bin/tmux"

[window]
# See https://github.com/alacritty/alacritty/issues/7465
# startup_mode = "Maximized"
