#!/usr/bin/env bash

set -euo pipefail

REGION="us"

token="$(gcloud auth print-access-token)"

if hash podman &> /dev/null; then
    echo "podman found"
    podman login \
        "https://${REGION}-docker.pkg.dev" \
        --username=oauth2accesstoken \
        --password-stdin \
        <<<"$token"
else
    echo "podman not found"
fi

if hash skopeo &> /dev/null; then
    echo "skopeo found"
    skopeo login \
        "https://${REGION}-docker.pkg.dev" \
        --username=oauth2accesstoken \
        --password-stdin \
        <<<"$token"
else
    echo "skopeo not found"
fi
