#!/usr/bin/env bash

set -euo pipefail

if [[ "$#" != 2 ]]; then
    echo "Usage: gsopt <INPUT> <OUTPUT>"
    exit 1
fi

readonly input="$1"
readonly output="$2"

if [[ "$input" == "$output" ]]; then
    echo "input and output must be different"
    exit 1
fi

exec gs \
    -dBATCH \
    -dCompatibilityLevel=1.7 \
    -dCompressFonts=true \
    -dCompressPages=true \
    -dDetectDuplicateImages=true \
    -dEmbedAllFonts=true \
    -dNOPAUSE \
    -dPDFSETTINGS=/ebook \
    -dSubsetFonts=true \
    -sDEVICE=pdfwrite \
    -sOutputFile="$output" \
    "$input"
