#!/usr/bin/env bash

set -euo pipefail

if [ "$#" -ne 2 ]; then
    echo "Usage: gsopt <INPUT> <OUTPUT>"
    exit 1
fi

input="$1"
output="$2"

exec gs \
    -dBATCH \
    -dCompatibilityLevel=1.7 \
    -dCompressFonts=true \
    -dCompressPages=true \
    -dDetectDuplicateImages=true \
    -dEmbedAllFonts=true \
    -dNOPAUSE \
    -dPDFSETTINGS=/ebook \
    -dSubsetFonts=true \
    -sDEVICE=pdfwrite \
    -sOutputFile="$output" \
    "$input"
