#!/usr/bin/env bash

set -euo pipefail

if [ "$#" -ne 2 ]; then
    echo "Usage: $(basename "$0") <INPUT> <OUTPUT>"
    exit 1
fi

input="$1"
output="$2"

if ! [[ "$output" =~ ^.*.svgz$ ]]; then
    echo "output must be a .svgz file"
    exit 1
fi

inkscape \
    --export-plain-svg \
    --export-text-to-path \
    --export-filename="-" \
    --vacuum-defs \
    "$input" \
| svgo \
    --input="-" \
    --output="-" \
| gzip \
    --stdout \
    --best \
> "$output"
