#!/usr/bin/env bash

set -euo pipefail

# check DEBUG statements
# use additional quotes here so we are able to commit THIS file with THIS filter (inception :D )
for FILE in `git diff --name-only --cached`; do
    # skip non-existing (i.e. deleted) files
    if [ -e "$FILE" ]; then
        set +e
        grep 'XXX''-DEBUG' "$FILE" 2>&1 >/dev/null
        status=$?
        set -e
        if [ $status -eq 0 ]; then
            echo "$FILE" ' contains XXX''-DEBUG'
            exit 1
        fi
    fi
done

exit 0
