" general vim setup
set nocompatible
set encoding=utf-8
set fileencoding=utf-8
set termencoding=utf-8
set lazyredraw
set mouse=a
set shell=/usr/bin/bash
set hidden

" neovim fixes
runtime! python_setup.vim

" undo/redo history
set history=100
silent !mkdir ~/.vim/undo > /dev/null 2>&1
set undodir=~/.vim/undo
set undofile

" shift, tab, indent, backspace
set backspace=indent,eol,start
set autoindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" faster command line commands
nnoremap ! :!

" split and navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
set splitbelow
set splitright

" better search
set incsearch
set ignorecase
set smartcase
set wrapscan

" look and feel
syntax enable
set number
set ruler
set showcmd
set list listchars=tab:→\ ,trail:·
set scrolloff=8
set sidescrolloff=10
set tabpagemax=32
set cursorline
set ttimeoutlen=0
set noerrorbells
set visualbell
set t_vb =

" bigger syntax scan range
autocmd BufEnter * :syntax sync minlines=500

" wildmenu
set wildmenu
set wildmode=list:longest,full

" ignores
set wildignore+=*.pyc

" folds
set foldmethod=syntax
set foldopen=block,hor,jump,mark,percent,quickfix,search,tag,undo
nmap <SPACE> za

" strip whitespaces @ safe (except diff files)
autocmd BufWritePre *
    \ if &filetype != "diff"
    \ | :%s/\s\+$//e
    \ | endif

" fix markdown editing
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

" figure out the system Python for Neovim
function GetWhichFirst(programs)
    let l:candidate=''
    for p in a:programs
        let l:candidate=substitute(system("which " . p), "\n", '', 'g')
        if l:candidate != ''
            break
        endif
    endfor
    return l:candidate
endfunction
function GetWhichSecond(programs)
    let l:candidate=''
    for p in a:programs
        let l:candidate=substitute(system("which -a " . p . " | head -n2 | tail -n1"), "\n", '', 'g')
        if l:candidate != ''
            break
        endif
    endfor
    return l:candidate
endfunction
let s:candidates_python2=['python2.7', 'python2']
let s:candidates_python3=['python3.7', 'python3.6', 'python3']
if exists("$VIRTUAL_ENV") || exists("$CONDA_PREFIX")
    let g:python_host_prog=GetWhichSecond(s:candidates_python2)
    let g:python3_host_prog=GetWhichSecond(s:candidates_python3)
else
    let g:python_host_prog=GetWhichFirst(s:candidates_python2)
    let g:python3_host_prog=GetWhichFirst(s:candidates_python3)
endif

" clipboard
set clipboard=unnamed
function! MyPaste()
    set paste
    normal "+p
    set nopaste
endfunction
nmap <silent> <C-p> :call MyPaste()<CR>
imap <silent> <C-p> <ESC>:call MyPaste()<CR>a
vmap <C-c> "+y

" vim-plug
call plug#begin('~/.local/share/neovim/plugged')
filetype off
Plug 'junegunn/vim-plug'

" restore_vim.vim
Plug 'vim-scripts/restore_view.vim'
let g:skipview_files = [
    \'.git/COMMIT_EDITMSG',
    \'.git/rebase-merge/git-rebase-todo'
    \]

" vimproc
" required for VimShell
Plug 'Shougo/vimproc'

" neocomplcache
" optional for VimShell
Plug 'Shougo/neocomplcache.vim'

" tomorrow theme
Plug 'chriskempson/base16-vim'
set rtp+=~/.vim/plugged/base16-vim
set background=dark
let base16colorspace=256
colorscheme base16-bright

" SudoRead and SudoWrite
Plug 'chrisbra/SudoEdit.vim'

" Pencil
Plug 'reedes/vim-pencil'

" airline
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
set laststatus=2
let g:airline_powerline_fonts = 1

" delimitMate
Plug 'Raimondi/delimitMate'
let delimitMate_expand_cr = 1
let delimitMate_expand_space = 1

" language server (autocompletion, warnings/errors)
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
let g:LanguageClient_serverCommands = {
    \ 'python': ['pyls'],
    \ 'rust': ['rustup', 'run', 'stable', 'rls'],
    \ }
let g:LanguageClient_selectionUI = 'fzf'
nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient_textDocument_rename()<CR>
nnoremap <silent> <F3> :call LanguageClient_textDocument_formatting()<CR>
nnoremap <silent> <F4> :call LanguageClient_textDocument_codeAction()<CR>

" fzf (required for LanguageClient)
Plug 'junegunn/fzf'

" auto-completion engine
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
autocmd BufEnter * call ncm2#enable_for_buffer()
set completeopt=noinsert,menuone,noselect
Plug 'ncm2/ncm2-bufword'
Plug 'ncm2/ncm2-path'
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <CR> (pumvisible() ? "\<c-y>\<cr>" : "\<CR>")
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif

" Snippets
Plug 'Shougo/neosnippet.vim'
Plug 'Shougo/neosnippet-snippets'
Plug 'honza/vim-snippets'
let g:neosnippet#enable_snipmate_compatibility = 1
let g:neosnippet#snippets_directory='~/.local/share/neovim/vim-snippets/snippets'
imap <C-j>     <Plug>(neosnippet_expand_or_jump)
smap <C-j>     <Plug>(neosnippet_expand_or_jump)
xmap <C-j>     <Plug>(neosnippet_expand_target)
imap <expr><TAB>
\ pumvisible() ? "\<C-n>" :
\ neosnippet#expandable_or_jumpable() ?
\    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
set conceallevel=2 concealcursor=niv
Plug 'ncm2/ncm2-neosnippet'

" PreserveNoEOL
" required by editorconfig to handle this specific rule
Plug 'vim-scripts/PreserveNoEOL'

" editorconfig
Plug 'editorconfig/editorconfig-vim'
let g:EditorConfig_exclude_patterns = ['fugitive://.*']
let g:EditorConfig_exec_path = '/usr/bin/editorconfig'

" VCS diffs
Plug 'mhinz/vim-signify'

" GIT commands
Plug 'tpope/vim-fugitive'
Plug 'rhysd/conflict-marker.vim'

" tcomment
Plug 'tomtom/tcomment_vim'

" VimShell
Plug 'Shougo/vimshell.vim'

" startify
Plug 'mhinz/vim-startify'
hi StartifyBracket ctermfg=240
hi StartifyFooter  ctermfg=111
hi StartifyHeader  ctermfg=203
hi StartifyNumber  ctermfg=215
hi StartifyPath    ctermfg=245
hi StartifySlash   ctermfg=240

" shebang filetype detection
Plug 'vitalk/vim-shebang'

" julia
Plug 'JuliaLang/julia-vim'
let g:julia_latex_to_unicode = 0

" rust
Plug 'rust-lang/rust.vim'

" numbertoggle
Plug 'jeffkreeftmeijer/vim-numbertoggle'

" CTRL-P
Plug 'ctrlpvim/ctrlp.vim'

" Ripgrep
Plug 'jremmen/vim-ripgrep'

" EasyMotion
Plug 'Lokaltog/vim-easymotion'

" distraction-free writing
" goyo and limelight
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
function! GoyoBefore()
    set nocursorline
    set wrap
    set linebreak
    set nolist
    set noshowmode
    set noshowcmd
    set scrolloff=999
    Limelight
endfunction

function! GoyoAfter()
    Limelight!
    set list
    set nolinebreak
    set nowrap
    set cursorline
    set showmode
    set showcmd
    set scrolloff=8
endfunction

let g:goyo_width = 120
let g:goyo_callbacks = [function('GoyoBefore'), function('GoyoAfter')]

" more text object
Plug 'vim-scripts/argtextobj.vim'
Plug 'bkad/CamelCaseMotion'
Plug 'michaeljsmith/vim-indent-object'

" expand region
Plug 'terryma/vim-expand-region'

" incremental search
Plug 'haya14busa/incsearch.vim'
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)
map <silent> <F8> :nohlsearch<CR>

" exchange
Plug 'tommcdo/vim-exchange'

" NrrwRgn
Plug 'chrisbra/NrrwRgn'

" better diff
Plug 'chrisbra/vim-diff-enhanced'

" sneak
Plug 'justinmk/vim-sneak'

" better Python indention
Plug 'Vimjas/vim-python-pep8-indent'

" undo-redo tree
Plug 'simnalamburt/vim-mundo'
nnoremap <silent> <F5> :MundoToggle<CR>

" NERDTree
Plug 'scrooloose/nerdtree'
nnoremap <silent> <F10> :NERDTreeToggle<CR>

" matchit
runtime! macros/matchit.vim

" spell check
autocmd BufWinEnter * let b:myLang=0
let g:myLangList=["nospell","de_de","en_us","es"]
function! ToggleSpell()
    let b:myLang=b:myLang+1
    if b:myLang>=len(g:myLangList) | let b:myLang=0 | endif
    if b:myLang==0
        setlocal nospell
    else
        execute "setlocal spell spelllang=".get(g:myLangList, b:myLang)
    endif
    echo "spell checking language:" g:myLangList[b:myLang]
endfunction
nmap <silent> <F7> :call ToggleSpell()<CR>
imap <silent> <F7> <ESC>:call ToggleSpell()<CR>a

" highlight overlong lines
" HINT: needs to go at the very bottom of the file
let &colorcolumn=join(range(121,999),",")

" activate filetype again
call plug#end()
filetype plugin indent on

