[aliases]
rebase_all = ["rebase", "-s", "all:roots(main@origin..@)", "-d", "main@origin"]
watch_log = [
    "util", "exec", "--",
    "watch", "--color", "--interval=1", "--no-title", "--",
    "jj", "log", "--color=always",
]

[snapshot]
# 10 MB
max-new-file-size = 10485760

[user]
email = "marco@crepererum.net"
name = "Marco Neumann"

[ui]
bookmark-list-sort-keys = ["committer-date-"]
default-command = ["log", "-r", "::@"]
diff-editor = ":builtin"
diff-formatter = ":git"
merge-editor = ":builtin"
pager = "delta"

